### ISSUE TITLE
Upload to S3

### ISSUE THREAD

**Issue by yuokada** [yuokada/embulk-output-orc#3]

**Comment by yuokada** [comment]
`DefaultAWSCredentialsProviderChain` or 

## References
- [AWSCredentialsProvider (AWS SDK for Java - 1.11.184)](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/AWSCredentialsProvider.html "AWSCredentialsProvider (AWS SDK for Java - 1.11.184)")
- http://lapped-lapped.blogspot.jp/2013/06/aws-java-sdk.html
- http://javatechnology.net/java/amazon-aws-accesskey-secretkey/

**Comment by yuokada** [comment]
## Reference
[llibra/embulk-output-s3: Embulk S3 output plugin](https://github.com/llibra/embulk-output-s3 "llibra/embulk-output-s3: Embulk S3 output plugin")

**Comment by sakama** [comment]
Hi.

You may be able to use [embulk-util-aws-credentials library](https://github.com/embulk/embulk-input-s3/tree/master/embulk-util-aws-credentials) to support AWS authentications.
This supports [various kinds of auth method](https://github.com/embulk/embulk-input-s3#configuration) so that I guess you'll be able to implement with less efforts.

This library is developing as a sub project of [embulk-input-s3 plugin](https://github.com/embulk/embulk-input-s3) and also be released to [bintray](https://bintray.com/embulk-input-s3/maven/embulk-util-aws-credentials).
You can find usage in [embulk-output-redshift](https://github.com/embulk/embulk-output-jdbc/blob/master/embulk-output-redshift/build.gradle#L7)

Regards.

**Comment by yuokada** [comment]
Thanks, I wil try to use it.
